name: Windows RDP via Ngrok

on:
  workflow_dispatch:   # <-- this makes the "Run workflow" button appear
  push:

jobs:
  rdp-setup:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Download and extract Ngrok
      shell: pwsh
      run: |
        Invoke-WebRequest "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath "$env:USERPROFILE" -Force
        Remove-Item ngrok.zip
        Copy-Item "$env:USERPROFILE\ngrok.exe" "$env:GITHUB_WORKSPACE"

    - name: Authenticate Ngrok
      shell: pwsh
      run: .\ngrok.exe authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

    - name: Enable RDP and Firewall
      shell: pwsh
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        New-NetFirewallRule -DisplayName "Allow RDP via Ngrok" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 3389 -ErrorAction SilentlyContinue

    - name: Create Admin User
      shell: pwsh
      run: |
        net user hasnain "${{ secrets.Password }}" /add
        net localgroup administrators hasnain /add

    - name: Start Ngrok Tunnel
      shell: pwsh
      run: |
        Start-Process -FilePath "$pwd\ngrok.exe" -ArgumentList "tcp 3389 --log=stdout" -NoNewWindow -RedirectStandardOutput ngrok.log

        $tunnelUrl = $null
        $timeout = 60
        while ($timeout -gt 0 -and -not $tunnelUrl) {
          Start-Sleep -Seconds 5
          $timeout -= 5
          try {
            $response = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels" -ErrorAction Stop
            $tunnelUrl = $response.tunnels[0].public_url -replace "tcp://", ""
          } catch {
            if (Test-Path ngrok.log) {
              $match = (Get-Content ngrok.log | Select-String -Pattern "tcp://([a-zA-Z0-9\.\-]+:\d+)").Matches
              if ($match.Count -gt 0) { $tunnelUrl = $match[0].Groups[1].Value }
            }
          }
        }

        if (-not $tunnelUrl) {
          Write-Host "::error::Ngrok tunnel could not be established"
          exit 1
        }

        Write-Host "============================================"
        Write-Host "||     ✅ RDP CONNECTION DETAILS         ||"
        Write-Host "============================================"
        Write-Host ("Address: {0}" -f $tunnelUrl)
        Write-Host "Username: admin"
        Write-Host ("Password: {0}" -f "${{ secrets.Password }}")
        Write-Host "--------------------------------------------"
        Write-Host "Instructions:"
        Write-Host "1. Press Win + R, type 'mstsc' and hit Enter"
        Write-Host ("2. Connect to: {0}" -f $tunnelUrl)
        Write-Host "3. Use credentials above"
        Write-Host "============================================"

        while ($true) { Start-Sleep -Seconds 300 }

    - name: Cleanup Ngrok
      if: always()
      shell: pwsh
      run: Stop-Process -Name "ngrok" -Force -ErrorAction SilentlyContinue
